name: CI/CD

on: 
  push:
    tags:
      - v*

jobs:
  flutter_test:
    name: Run Flutter analyze and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      - run: dart format .
      - run: flutter test --coverage
      - run: flutter test --machine > test-results.json
      - uses: actions/upload-artifact@v3  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: test-results.json

      - uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          min_coverage: 0

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk
      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: my apk
          path: build/app/outputs/bundle/release/app-release.apk

  email:
    name: Enviando Email
    needs: [build_appbundle]
    runs-on: ubuntu-latest
    steps:
    - name: Download APK Artifact
      uses: actions/download-artifact@v2
      with:
        name: my apk
    - name: Send Email with APK Attachment
      uses: dawidd6/action-send-mail@v3.3.0
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: my apk
        body: Please find attached the APK.
        from: 'joseernestosantosmoraes@gmail.com'
        to: 'jose.ernesto.santos07@aluno.ifce.edu.br'
        attachments: 'app-debug.apk'